### ISSUE TITLE
How does app.auth.use work?

### ISSUE THREAD

**Issue by Removed-5an** [adamhalasz/diet-auth#1]
When looking at your code I'm not entirely sure how this works...
- How does app have a property/method auth?
- Where does the method use come from? It doesn't seem like your module.exports function exposes any method called use? All it does is export an anonymous function.

**Comment by adamhalasz** [comment]
Hey! My bad! The documentation was outdated. There is **no** `app.auth.use` it should look like this:

``` javascript
var auth  = require('diet-auth')(app) // <-- pass in your app server instance

// Setup Auth Service
var facebook = auth('facebook', {   // <-- just use the returned auth function to configure services
    id      : 'yourId',             // facebook app id
    secret  : 'yourSecret',         // facebook app secret
    scope   : 'email'               // specify facebook scopes
})
```

The github and npm repo was updated. Feel free to download the new v.1.2.1 version with the corrected documentation. Let me know if you have any other questions.

**Comment by Removed-5an** [comment]
Thanks for clarifying! I thought there was some require magic going on that I didn't understand.

By the way, I notice that in your API section of the documentation you still mention auth.use ;-).

**Comment by adamhalasz** [comment]
Oups! You're right I just fixed it. Thanks a lot :P Let me know if you find anything else or if you have any other questions.

By the way did you make it work with either facebook or google?

**Comment by Removed-5an** [comment]
I was just having a brief look at diet and it's modules. I really loved what I saw by the way! Unfortunately I don't really have a lot of time available nowadays, so haven't been able tot play around with it yet.

**Comment by adamhalasz** [comment]
That's cool! I'm really glad you like it! :smiley:
